### ISSUE TITLE
Project generation fails in golang 1.9.4

### ISSUE THREAD

**Issue by mithucste30** [gobuffalo/buffalo#1776]
When I tried to create new project at this step it failed
at this step

```
go get github.com/monoculum/formam
errors.go:25:8: undefined: strings.Builder
```
seems like its expected cause it requires golang 1.10 or later
https://github.com/monoculum/formam#formam

After i upgraded go version to 1.12 it worked fine.

Buffalo says it needs golang 1.8, but while the generation fails, isn't that misleading?

OS: Ubuntu 19.04

**Comment by markbates** [comment]
Where do you see `1.8`? I ask because that's incorrect information, and it should be corrected.

 Buffalo has always had a "last two" revisions policy. Currently, https://gobuffalo.io/en/ lists `v1.10.4`. That's going to be upgraded to `v1.12` today.

I'm closing this as this is expected behavior.
